# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: A Test master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Download and install KTreemap fork
      run: git clone https://bitbucket.org/atlassian/ktreemap ktreemap
        - (cd ktreemap; git checkout ktreemap-1.1.0-atlassian-01; mvn install)

    - name: Prepare repacked third party libraries
      run: mvn install -f clover-core-libs/jarjar/pom.xml
        - mvn install -Prepack -f clover-core-libs/pom.xml
        - mvn install -Prepack -f clover-idea/clover-jtreemap/pom.xml
 
    - name: Run tests (except Eclipse and IDEA)
      run: ant -noinput -buildfile build.xml clover-core.test clover-ant.test groovy.test
